//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DobbleGame.ServidorDobble {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServidorDobble.IGestionJugador")]
    public interface IGestionJugador {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionJugador/Registro", ReplyAction="http://tempuri.org/IGestionJugador/RegistroResponse")]
        bool Registro();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionJugador/Registro", ReplyAction="http://tempuri.org/IGestionJugador/RegistroResponse")]
        System.Threading.Tasks.Task<bool> RegistroAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGestionJugadorChannel : DobbleGame.ServidorDobble.IGestionJugador, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GestionJugadorClient : System.ServiceModel.ClientBase<DobbleGame.ServidorDobble.IGestionJugador>, DobbleGame.ServidorDobble.IGestionJugador {
        
        public GestionJugadorClient() {
        }
        
        public GestionJugadorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GestionJugadorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestionJugadorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestionJugadorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Registro() {
            return base.Channel.Registro();
        }
        
        public System.Threading.Tasks.Task<bool> RegistroAsync() {
            return base.Channel.RegistroAsync();
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServidorDobble.IGestionSala", CallbackContract=typeof(DobbleGame.ServidorDobble.IGestionSalaCallback))]
    public interface IGestionSala {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGestionSala/EnviarMensajeSala")]
        void EnviarMensajeSala(string mensaje);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGestionSala/EnviarMensajeSala")]
        System.Threading.Tasks.Task EnviarMensajeSalaAsync(string mensaje);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGestionSalaCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGestionSala/SalaResponse")]
        void SalaResponse(string respuesta);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGestionSalaChannel : DobbleGame.ServidorDobble.IGestionSala, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GestionSalaClient : System.ServiceModel.DuplexClientBase<DobbleGame.ServidorDobble.IGestionSala>, DobbleGame.ServidorDobble.IGestionSala {
        
        public GestionSalaClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public GestionSalaClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public GestionSalaClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public GestionSalaClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public GestionSalaClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void EnviarMensajeSala(string mensaje) {
            base.Channel.EnviarMensajeSala(mensaje);
        }
        
        public System.Threading.Tasks.Task EnviarMensajeSalaAsync(string mensaje) {
            return base.Channel.EnviarMensajeSalaAsync(mensaje);
        }
    }
}
