//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DobbleGame.Servidor {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CuentaUsuario", Namespace="http://schemas.datacontract.org/2004/07/Logica")]
    [System.SerializableAttribute()]
    public partial class CuentaUsuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContraseñaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] FotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdCuentaUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PuntajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contraseña {
            get {
                return this.ContraseñaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContraseñaField, value) != true)) {
                    this.ContraseñaField = value;
                    this.RaisePropertyChanged("Contraseña");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo {
            get {
                return this.CorreoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoField, value) != true)) {
                    this.CorreoField = value;
                    this.RaisePropertyChanged("Correo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Foto {
            get {
                return this.FotoField;
            }
            set {
                if ((object.ReferenceEquals(this.FotoField, value) != true)) {
                    this.FotoField = value;
                    this.RaisePropertyChanged("Foto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCuentaUsuario {
            get {
                return this.IdCuentaUsuarioField;
            }
            set {
                if ((this.IdCuentaUsuarioField.Equals(value) != true)) {
                    this.IdCuentaUsuarioField = value;
                    this.RaisePropertyChanged("IdCuentaUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Puntaje {
            get {
                return this.PuntajeField;
            }
            set {
                if ((this.PuntajeField.Equals(value) != true)) {
                    this.PuntajeField = value;
                    this.RaisePropertyChanged("Puntaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaServicioOfboolean", Namespace="http://schemas.datacontract.org/2004/07/Logica")]
    [System.SerializableAttribute()]
    public partial class RespuestaServicioOfboolean : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ErrorBDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ExitosoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ResultadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ErrorBD {
            get {
                return this.ErrorBDField;
            }
            set {
                if ((this.ErrorBDField.Equals(value) != true)) {
                    this.ErrorBDField = value;
                    this.RaisePropertyChanged("ErrorBD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Exitoso {
            get {
                return this.ExitosoField;
            }
            set {
                if ((this.ExitosoField.Equals(value) != true)) {
                    this.ExitosoField = value;
                    this.RaisePropertyChanged("Exitoso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Resultado {
            get {
                return this.ResultadoField;
            }
            set {
                if ((this.ResultadoField.Equals(value) != true)) {
                    this.ResultadoField = value;
                    this.RaisePropertyChanged("Resultado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaServicioOfCuentaUsuario6jbaXeYD", Namespace="http://schemas.datacontract.org/2004/07/Logica")]
    [System.SerializableAttribute()]
    public partial class RespuestaServicioOfCuentaUsuario6jbaXeYD : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ErrorBDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ExitosoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DobbleGame.Servidor.CuentaUsuario ResultadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ErrorBD {
            get {
                return this.ErrorBDField;
            }
            set {
                if ((this.ErrorBDField.Equals(value) != true)) {
                    this.ErrorBDField = value;
                    this.RaisePropertyChanged("ErrorBD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Exitoso {
            get {
                return this.ExitosoField;
            }
            set {
                if ((this.ExitosoField.Equals(value) != true)) {
                    this.ExitosoField = value;
                    this.RaisePropertyChanged("Exitoso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DobbleGame.Servidor.CuentaUsuario Resultado {
            get {
                return this.ResultadoField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultadoField, value) != true)) {
                    this.ResultadoField = value;
                    this.RaisePropertyChanged("Resultado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Jugador", Namespace="http://schemas.datacontract.org/2004/07/Logica")]
    [System.SerializableAttribute()]
    public partial class Jugador : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EsAnfitrionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] FotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumeroJugadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PuntajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PuntosEnPartidaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EsAnfitrion {
            get {
                return this.EsAnfitrionField;
            }
            set {
                if ((this.EsAnfitrionField.Equals(value) != true)) {
                    this.EsAnfitrionField = value;
                    this.RaisePropertyChanged("EsAnfitrion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Foto {
            get {
                return this.FotoField;
            }
            set {
                if ((object.ReferenceEquals(this.FotoField, value) != true)) {
                    this.FotoField = value;
                    this.RaisePropertyChanged("Foto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumeroJugador {
            get {
                return this.NumeroJugadorField;
            }
            set {
                if ((this.NumeroJugadorField.Equals(value) != true)) {
                    this.NumeroJugadorField = value;
                    this.RaisePropertyChanged("NumeroJugador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Puntaje {
            get {
                return this.PuntajeField;
            }
            set {
                if ((this.PuntajeField.Equals(value) != true)) {
                    this.PuntajeField = value;
                    this.RaisePropertyChanged("Puntaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PuntosEnPartida {
            get {
                return this.PuntosEnPartidaField;
            }
            set {
                if ((this.PuntosEnPartidaField.Equals(value) != true)) {
                    this.PuntosEnPartidaField = value;
                    this.RaisePropertyChanged("PuntosEnPartida");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaServicioOfArrayOfAmistad6jbaXeYD", Namespace="http://schemas.datacontract.org/2004/07/Logica")]
    [System.SerializableAttribute()]
    public partial class RespuestaServicioOfArrayOfAmistad6jbaXeYD : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ErrorBDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ExitosoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DobbleGame.Servidor.Amistad[] ResultadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ErrorBD {
            get {
                return this.ErrorBDField;
            }
            set {
                if ((this.ErrorBDField.Equals(value) != true)) {
                    this.ErrorBDField = value;
                    this.RaisePropertyChanged("ErrorBD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Exitoso {
            get {
                return this.ExitosoField;
            }
            set {
                if ((this.ExitosoField.Equals(value) != true)) {
                    this.ExitosoField = value;
                    this.RaisePropertyChanged("Exitoso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DobbleGame.Servidor.Amistad[] Resultado {
            get {
                return this.ResultadoField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultadoField, value) != true)) {
                    this.ResultadoField = value;
                    this.RaisePropertyChanged("Resultado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Amistad", Namespace="http://schemas.datacontract.org/2004/07/Logica")]
    [System.SerializableAttribute()]
    public partial class Amistad : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UsuarioAmigoIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UsuarioPrincipalIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool estadoSolicitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idAmistadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UsuarioAmigoId {
            get {
                return this.UsuarioAmigoIdField;
            }
            set {
                if ((this.UsuarioAmigoIdField.Equals(value) != true)) {
                    this.UsuarioAmigoIdField = value;
                    this.RaisePropertyChanged("UsuarioAmigoId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UsuarioPrincipalId {
            get {
                return this.UsuarioPrincipalIdField;
            }
            set {
                if ((this.UsuarioPrincipalIdField.Equals(value) != true)) {
                    this.UsuarioPrincipalIdField = value;
                    this.RaisePropertyChanged("UsuarioPrincipalId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool estadoSolicitud {
            get {
                return this.estadoSolicitudField;
            }
            set {
                if ((this.estadoSolicitudField.Equals(value) != true)) {
                    this.estadoSolicitudField = value;
                    this.RaisePropertyChanged("estadoSolicitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idAmistad {
            get {
                return this.idAmistadField;
            }
            set {
                if ((this.idAmistadField.Equals(value) != true)) {
                    this.idAmistadField = value;
                    this.RaisePropertyChanged("idAmistad");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaServicioOfAmistad6jbaXeYD", Namespace="http://schemas.datacontract.org/2004/07/Logica")]
    [System.SerializableAttribute()]
    public partial class RespuestaServicioOfAmistad6jbaXeYD : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ErrorBDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ExitosoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DobbleGame.Servidor.Amistad ResultadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ErrorBD {
            get {
                return this.ErrorBDField;
            }
            set {
                if ((this.ErrorBDField.Equals(value) != true)) {
                    this.ErrorBDField = value;
                    this.RaisePropertyChanged("ErrorBD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Exitoso {
            get {
                return this.ExitosoField;
            }
            set {
                if ((this.ExitosoField.Equals(value) != true)) {
                    this.ExitosoField = value;
                    this.RaisePropertyChanged("Exitoso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DobbleGame.Servidor.Amistad Resultado {
            get {
                return this.ResultadoField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultadoField, value) != true)) {
                    this.ResultadoField = value;
                    this.RaisePropertyChanged("Resultado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Carta", Namespace="http://schemas.datacontract.org/2004/07/Logica")]
    [System.SerializableAttribute()]
    public partial class Carta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DobbleGame.Servidor.Icono[] IconosField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DobbleGame.Servidor.Icono[] Iconos {
            get {
                return this.IconosField;
            }
            set {
                if ((object.ReferenceEquals(this.IconosField, value) != true)) {
                    this.IconosField = value;
                    this.RaisePropertyChanged("Iconos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Icono", Namespace="http://schemas.datacontract.org/2004/07/Logica")]
    [System.SerializableAttribute()]
    public partial class Icono : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdIconoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RutaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdIcono {
            get {
                return this.IdIconoField;
            }
            set {
                if ((this.IdIconoField.Equals(value) != true)) {
                    this.IdIconoField = value;
                    this.RaisePropertyChanged("IdIcono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ruta {
            get {
                return this.RutaField;
            }
            set {
                if ((object.ReferenceEquals(this.RutaField, value) != true)) {
                    this.RutaField = value;
                    this.RaisePropertyChanged("Ruta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Servidor.IGestionJugador")]
    public interface IGestionJugador {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionJugador/RegistrarUsuario", ReplyAction="http://tempuri.org/IGestionJugador/RegistrarUsuarioResponse")]
        DobbleGame.Servidor.RespuestaServicioOfboolean RegistrarUsuario(DobbleGame.Servidor.CuentaUsuario cuentaUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionJugador/RegistrarUsuario", ReplyAction="http://tempuri.org/IGestionJugador/RegistrarUsuarioResponse")]
        System.Threading.Tasks.Task<DobbleGame.Servidor.RespuestaServicioOfboolean> RegistrarUsuarioAsync(DobbleGame.Servidor.CuentaUsuario cuentaUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionJugador/ExisteNombreUsuario", ReplyAction="http://tempuri.org/IGestionJugador/ExisteNombreUsuarioResponse")]
        DobbleGame.Servidor.RespuestaServicioOfboolean ExisteNombreUsuario(string nombreUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionJugador/ExisteNombreUsuario", ReplyAction="http://tempuri.org/IGestionJugador/ExisteNombreUsuarioResponse")]
        System.Threading.Tasks.Task<DobbleGame.Servidor.RespuestaServicioOfboolean> ExisteNombreUsuarioAsync(string nombreUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionJugador/ExisteCorreoAsociado", ReplyAction="http://tempuri.org/IGestionJugador/ExisteCorreoAsociadoResponse")]
        DobbleGame.Servidor.RespuestaServicioOfboolean ExisteCorreoAsociado(string correoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionJugador/ExisteCorreoAsociado", ReplyAction="http://tempuri.org/IGestionJugador/ExisteCorreoAsociadoResponse")]
        System.Threading.Tasks.Task<DobbleGame.Servidor.RespuestaServicioOfboolean> ExisteCorreoAsociadoAsync(string correoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionJugador/IniciarSesionJugador", ReplyAction="http://tempuri.org/IGestionJugador/IniciarSesionJugadorResponse")]
        DobbleGame.Servidor.RespuestaServicioOfCuentaUsuario6jbaXeYD IniciarSesionJugador(string nombreUsuario, string contraseña);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionJugador/IniciarSesionJugador", ReplyAction="http://tempuri.org/IGestionJugador/IniciarSesionJugadorResponse")]
        System.Threading.Tasks.Task<DobbleGame.Servidor.RespuestaServicioOfCuentaUsuario6jbaXeYD> IniciarSesionJugadorAsync(string nombreUsuario, string contraseña);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGestionJugador/CerrarSesionJugador")]
        void CerrarSesionJugador(string nombreUsuario, string mensaje);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGestionJugador/CerrarSesionJugador")]
        System.Threading.Tasks.Task CerrarSesionJugadorAsync(string nombreUsuario, string mensaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionJugador/ModificarNombreUsuario", ReplyAction="http://tempuri.org/IGestionJugador/ModificarNombreUsuarioResponse")]
        DobbleGame.Servidor.RespuestaServicioOfboolean ModificarNombreUsuario(int idCuenta, string nombreUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionJugador/ModificarNombreUsuario", ReplyAction="http://tempuri.org/IGestionJugador/ModificarNombreUsuarioResponse")]
        System.Threading.Tasks.Task<DobbleGame.Servidor.RespuestaServicioOfboolean> ModificarNombreUsuarioAsync(int idCuenta, string nombreUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionJugador/ModificarContraseñaUsuario", ReplyAction="http://tempuri.org/IGestionJugador/ModificarContraseñaUsuarioResponse")]
        DobbleGame.Servidor.RespuestaServicioOfboolean ModificarContraseñaUsuario(int idCuenta, string contraseñaUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionJugador/ModificarContraseñaUsuario", ReplyAction="http://tempuri.org/IGestionJugador/ModificarContraseñaUsuarioResponse")]
        System.Threading.Tasks.Task<DobbleGame.Servidor.RespuestaServicioOfboolean> ModificarContraseñaUsuarioAsync(int idCuenta, string contraseñaUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionJugador/ModificarFotoUsuario", ReplyAction="http://tempuri.org/IGestionJugador/ModificarFotoUsuarioResponse")]
        DobbleGame.Servidor.RespuestaServicioOfboolean ModificarFotoUsuario(int idCuenta, byte[] fotoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionJugador/ModificarFotoUsuario", ReplyAction="http://tempuri.org/IGestionJugador/ModificarFotoUsuarioResponse")]
        System.Threading.Tasks.Task<DobbleGame.Servidor.RespuestaServicioOfboolean> ModificarFotoUsuarioAsync(int idCuenta, byte[] fotoUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionJugador/ValidarContraseña", ReplyAction="http://tempuri.org/IGestionJugador/ValidarContraseñaResponse")]
        DobbleGame.Servidor.RespuestaServicioOfboolean ValidarContraseña(int idCuenta, string contraseñaUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionJugador/ValidarContraseña", ReplyAction="http://tempuri.org/IGestionJugador/ValidarContraseñaResponse")]
        System.Threading.Tasks.Task<DobbleGame.Servidor.RespuestaServicioOfboolean> ValidarContraseñaAsync(int idCuenta, string contraseñaUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionJugador/ObtenerUsuarioPorCorreo", ReplyAction="http://tempuri.org/IGestionJugador/ObtenerUsuarioPorCorreoResponse")]
        DobbleGame.Servidor.RespuestaServicioOfCuentaUsuario6jbaXeYD ObtenerUsuarioPorCorreo(string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionJugador/ObtenerUsuarioPorCorreo", ReplyAction="http://tempuri.org/IGestionJugador/ObtenerUsuarioPorCorreoResponse")]
        System.Threading.Tasks.Task<DobbleGame.Servidor.RespuestaServicioOfCuentaUsuario6jbaXeYD> ObtenerUsuarioPorCorreoAsync(string correo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGestionJugadorChannel : DobbleGame.Servidor.IGestionJugador, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GestionJugadorClient : System.ServiceModel.ClientBase<DobbleGame.Servidor.IGestionJugador>, DobbleGame.Servidor.IGestionJugador {
        
        public GestionJugadorClient() {
        }
        
        public GestionJugadorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GestionJugadorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestionJugadorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestionJugadorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DobbleGame.Servidor.RespuestaServicioOfboolean RegistrarUsuario(DobbleGame.Servidor.CuentaUsuario cuentaUsuario) {
            return base.Channel.RegistrarUsuario(cuentaUsuario);
        }
        
        public System.Threading.Tasks.Task<DobbleGame.Servidor.RespuestaServicioOfboolean> RegistrarUsuarioAsync(DobbleGame.Servidor.CuentaUsuario cuentaUsuario) {
            return base.Channel.RegistrarUsuarioAsync(cuentaUsuario);
        }
        
        public DobbleGame.Servidor.RespuestaServicioOfboolean ExisteNombreUsuario(string nombreUsuario) {
            return base.Channel.ExisteNombreUsuario(nombreUsuario);
        }
        
        public System.Threading.Tasks.Task<DobbleGame.Servidor.RespuestaServicioOfboolean> ExisteNombreUsuarioAsync(string nombreUsuario) {
            return base.Channel.ExisteNombreUsuarioAsync(nombreUsuario);
        }
        
        public DobbleGame.Servidor.RespuestaServicioOfboolean ExisteCorreoAsociado(string correoUsuario) {
            return base.Channel.ExisteCorreoAsociado(correoUsuario);
        }
        
        public System.Threading.Tasks.Task<DobbleGame.Servidor.RespuestaServicioOfboolean> ExisteCorreoAsociadoAsync(string correoUsuario) {
            return base.Channel.ExisteCorreoAsociadoAsync(correoUsuario);
        }
        
        public DobbleGame.Servidor.RespuestaServicioOfCuentaUsuario6jbaXeYD IniciarSesionJugador(string nombreUsuario, string contraseña) {
            return base.Channel.IniciarSesionJugador(nombreUsuario, contraseña);
        }
        
        public System.Threading.Tasks.Task<DobbleGame.Servidor.RespuestaServicioOfCuentaUsuario6jbaXeYD> IniciarSesionJugadorAsync(string nombreUsuario, string contraseña) {
            return base.Channel.IniciarSesionJugadorAsync(nombreUsuario, contraseña);
        }
        
        public void CerrarSesionJugador(string nombreUsuario, string mensaje) {
            base.Channel.CerrarSesionJugador(nombreUsuario, mensaje);
        }
        
        public System.Threading.Tasks.Task CerrarSesionJugadorAsync(string nombreUsuario, string mensaje) {
            return base.Channel.CerrarSesionJugadorAsync(nombreUsuario, mensaje);
        }
        
        public DobbleGame.Servidor.RespuestaServicioOfboolean ModificarNombreUsuario(int idCuenta, string nombreUsuario) {
            return base.Channel.ModificarNombreUsuario(idCuenta, nombreUsuario);
        }
        
        public System.Threading.Tasks.Task<DobbleGame.Servidor.RespuestaServicioOfboolean> ModificarNombreUsuarioAsync(int idCuenta, string nombreUsuario) {
            return base.Channel.ModificarNombreUsuarioAsync(idCuenta, nombreUsuario);
        }
        
        public DobbleGame.Servidor.RespuestaServicioOfboolean ModificarContraseñaUsuario(int idCuenta, string contraseñaUsuario) {
            return base.Channel.ModificarContraseñaUsuario(idCuenta, contraseñaUsuario);
        }
        
        public System.Threading.Tasks.Task<DobbleGame.Servidor.RespuestaServicioOfboolean> ModificarContraseñaUsuarioAsync(int idCuenta, string contraseñaUsuario) {
            return base.Channel.ModificarContraseñaUsuarioAsync(idCuenta, contraseñaUsuario);
        }
        
        public DobbleGame.Servidor.RespuestaServicioOfboolean ModificarFotoUsuario(int idCuenta, byte[] fotoUsuario) {
            return base.Channel.ModificarFotoUsuario(idCuenta, fotoUsuario);
        }
        
        public System.Threading.Tasks.Task<DobbleGame.Servidor.RespuestaServicioOfboolean> ModificarFotoUsuarioAsync(int idCuenta, byte[] fotoUsuario) {
            return base.Channel.ModificarFotoUsuarioAsync(idCuenta, fotoUsuario);
        }
        
        public DobbleGame.Servidor.RespuestaServicioOfboolean ValidarContraseña(int idCuenta, string contraseñaUsuario) {
            return base.Channel.ValidarContraseña(idCuenta, contraseñaUsuario);
        }
        
        public System.Threading.Tasks.Task<DobbleGame.Servidor.RespuestaServicioOfboolean> ValidarContraseñaAsync(int idCuenta, string contraseñaUsuario) {
            return base.Channel.ValidarContraseñaAsync(idCuenta, contraseñaUsuario);
        }
        
        public DobbleGame.Servidor.RespuestaServicioOfCuentaUsuario6jbaXeYD ObtenerUsuarioPorCorreo(string correo) {
            return base.Channel.ObtenerUsuarioPorCorreo(correo);
        }
        
        public System.Threading.Tasks.Task<DobbleGame.Servidor.RespuestaServicioOfCuentaUsuario6jbaXeYD> ObtenerUsuarioPorCorreoAsync(string correo) {
            return base.Channel.ObtenerUsuarioPorCorreoAsync(correo);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Servidor.IGestionSala", CallbackContract=typeof(DobbleGame.Servidor.IGestionSalaCallback))]
    public interface IGestionSala {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionSala/GenerarCodigoNuevaSala", ReplyAction="http://tempuri.org/IGestionSala/GenerarCodigoNuevaSalaResponse")]
        string GenerarCodigoNuevaSala();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionSala/GenerarCodigoNuevaSala", ReplyAction="http://tempuri.org/IGestionSala/GenerarCodigoNuevaSalaResponse")]
        System.Threading.Tasks.Task<string> GenerarCodigoNuevaSalaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionSala/CrearNuevaSala", ReplyAction="http://tempuri.org/IGestionSala/CrearNuevaSalaResponse")]
        bool CrearNuevaSala(string nombreUsuario, string codigoSala);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionSala/CrearNuevaSala", ReplyAction="http://tempuri.org/IGestionSala/CrearNuevaSalaResponse")]
        System.Threading.Tasks.Task<bool> CrearNuevaSalaAsync(string nombreUsuario, string codigoSala);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionSala/UnirseASala", ReplyAction="http://tempuri.org/IGestionSala/UnirseASalaResponse")]
        bool UnirseASala(string nombreUsuario, string codigoSala, string mensaje, bool esAnfitrion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionSala/UnirseASala", ReplyAction="http://tempuri.org/IGestionSala/UnirseASalaResponse")]
        System.Threading.Tasks.Task<bool> UnirseASalaAsync(string nombreUsuario, string codigoSala, string mensaje, bool esAnfitrion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionSala/AbandonarSala", ReplyAction="http://tempuri.org/IGestionSala/AbandonarSalaResponse")]
        bool AbandonarSala(string nombreUsuario, string codigoSala, string mensaje);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionSala/AbandonarSala", ReplyAction="http://tempuri.org/IGestionSala/AbandonarSalaResponse")]
        System.Threading.Tasks.Task<bool> AbandonarSalaAsync(string nombreUsuario, string codigoSala, string mensaje);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGestionSala/ExpulsarJugador")]
        void ExpulsarJugador(string nombreUsuario, string codigoSala, string mensaje);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGestionSala/ExpulsarJugador")]
        System.Threading.Tasks.Task ExpulsarJugadorAsync(string nombreUsuario, string codigoSala, string mensaje);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGestionSala/EnviarMensajeSala")]
        void EnviarMensajeSala(string nombreUsuario, string codigoSala, string mensaje);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGestionSala/EnviarMensajeSala")]
        System.Threading.Tasks.Task EnviarMensajeSalaAsync(string nombreUsuario, string codigoSala, string mensaje);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGestionSala/EnviarMensajeConexionSala")]
        void EnviarMensajeConexionSala(string nombreUsuario, string codigoSala, string mensaje);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGestionSala/EnviarMensajeConexionSala")]
        System.Threading.Tasks.Task EnviarMensajeConexionSalaAsync(string nombreUsuario, string codigoSala, string mensaje);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGestionSala/NotificarUsuarioConectado")]
        void NotificarUsuarioConectado(string codigoSala);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGestionSala/NotificarUsuarioConectado")]
        System.Threading.Tasks.Task NotificarUsuarioConectadoAsync(string codigoSala);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionSala/HayEspacioSala", ReplyAction="http://tempuri.org/IGestionSala/HayEspacioSalaResponse")]
        bool HayEspacioSala(string codigoSala);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionSala/HayEspacioSala", ReplyAction="http://tempuri.org/IGestionSala/HayEspacioSalaResponse")]
        System.Threading.Tasks.Task<bool> HayEspacioSalaAsync(string codigoSala);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionSala/ExisteSala", ReplyAction="http://tempuri.org/IGestionSala/ExisteSalaResponse")]
        bool ExisteSala(string codigoSala);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionSala/ExisteSala", ReplyAction="http://tempuri.org/IGestionSala/ExisteSalaResponse")]
        System.Threading.Tasks.Task<bool> ExisteSalaAsync(string codigoSala);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionSala/EsSalaDisponible", ReplyAction="http://tempuri.org/IGestionSala/EsSalaDisponibleResponse")]
        bool EsSalaDisponible(string codigoSala);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionSala/EsSalaDisponible", ReplyAction="http://tempuri.org/IGestionSala/EsSalaDisponibleResponse")]
        System.Threading.Tasks.Task<bool> EsSalaDisponibleAsync(string codigoSala);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGestionSala/CambiarVentanaParaTodos")]
        void CambiarVentanaParaTodos(string codigoSala);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGestionSala/CambiarVentanaParaTodos")]
        System.Threading.Tasks.Task CambiarVentanaParaTodosAsync(string codigoSala);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGestionSalaCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGestionSala/MostrarMensajeSala")]
        void MostrarMensajeSala(string mensaje);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGestionSala/ActualizarUsuariosConectados")]
        void ActualizarUsuariosConectados(DobbleGame.Servidor.Jugador[] usuariosConectados);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGestionSala/ConvertirEnAnfitrion")]
        void ConvertirEnAnfitrion();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGestionSala/NotificarExpulsionAJugador")]
        void NotificarExpulsionAJugador();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGestionSala/CambiarVentana")]
        void CambiarVentana();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGestionSalaChannel : DobbleGame.Servidor.IGestionSala, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GestionSalaClient : System.ServiceModel.DuplexClientBase<DobbleGame.Servidor.IGestionSala>, DobbleGame.Servidor.IGestionSala {
        
        public GestionSalaClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public GestionSalaClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public GestionSalaClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public GestionSalaClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public GestionSalaClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public string GenerarCodigoNuevaSala() {
            return base.Channel.GenerarCodigoNuevaSala();
        }
        
        public System.Threading.Tasks.Task<string> GenerarCodigoNuevaSalaAsync() {
            return base.Channel.GenerarCodigoNuevaSalaAsync();
        }
        
        public bool CrearNuevaSala(string nombreUsuario, string codigoSala) {
            return base.Channel.CrearNuevaSala(nombreUsuario, codigoSala);
        }
        
        public System.Threading.Tasks.Task<bool> CrearNuevaSalaAsync(string nombreUsuario, string codigoSala) {
            return base.Channel.CrearNuevaSalaAsync(nombreUsuario, codigoSala);
        }
        
        public bool UnirseASala(string nombreUsuario, string codigoSala, string mensaje, bool esAnfitrion) {
            return base.Channel.UnirseASala(nombreUsuario, codigoSala, mensaje, esAnfitrion);
        }
        
        public System.Threading.Tasks.Task<bool> UnirseASalaAsync(string nombreUsuario, string codigoSala, string mensaje, bool esAnfitrion) {
            return base.Channel.UnirseASalaAsync(nombreUsuario, codigoSala, mensaje, esAnfitrion);
        }
        
        public bool AbandonarSala(string nombreUsuario, string codigoSala, string mensaje) {
            return base.Channel.AbandonarSala(nombreUsuario, codigoSala, mensaje);
        }
        
        public System.Threading.Tasks.Task<bool> AbandonarSalaAsync(string nombreUsuario, string codigoSala, string mensaje) {
            return base.Channel.AbandonarSalaAsync(nombreUsuario, codigoSala, mensaje);
        }
        
        public void ExpulsarJugador(string nombreUsuario, string codigoSala, string mensaje) {
            base.Channel.ExpulsarJugador(nombreUsuario, codigoSala, mensaje);
        }
        
        public System.Threading.Tasks.Task ExpulsarJugadorAsync(string nombreUsuario, string codigoSala, string mensaje) {
            return base.Channel.ExpulsarJugadorAsync(nombreUsuario, codigoSala, mensaje);
        }
        
        public void EnviarMensajeSala(string nombreUsuario, string codigoSala, string mensaje) {
            base.Channel.EnviarMensajeSala(nombreUsuario, codigoSala, mensaje);
        }
        
        public System.Threading.Tasks.Task EnviarMensajeSalaAsync(string nombreUsuario, string codigoSala, string mensaje) {
            return base.Channel.EnviarMensajeSalaAsync(nombreUsuario, codigoSala, mensaje);
        }
        
        public void EnviarMensajeConexionSala(string nombreUsuario, string codigoSala, string mensaje) {
            base.Channel.EnviarMensajeConexionSala(nombreUsuario, codigoSala, mensaje);
        }
        
        public System.Threading.Tasks.Task EnviarMensajeConexionSalaAsync(string nombreUsuario, string codigoSala, string mensaje) {
            return base.Channel.EnviarMensajeConexionSalaAsync(nombreUsuario, codigoSala, mensaje);
        }
        
        public void NotificarUsuarioConectado(string codigoSala) {
            base.Channel.NotificarUsuarioConectado(codigoSala);
        }
        
        public System.Threading.Tasks.Task NotificarUsuarioConectadoAsync(string codigoSala) {
            return base.Channel.NotificarUsuarioConectadoAsync(codigoSala);
        }
        
        public bool HayEspacioSala(string codigoSala) {
            return base.Channel.HayEspacioSala(codigoSala);
        }
        
        public System.Threading.Tasks.Task<bool> HayEspacioSalaAsync(string codigoSala) {
            return base.Channel.HayEspacioSalaAsync(codigoSala);
        }
        
        public bool ExisteSala(string codigoSala) {
            return base.Channel.ExisteSala(codigoSala);
        }
        
        public System.Threading.Tasks.Task<bool> ExisteSalaAsync(string codigoSala) {
            return base.Channel.ExisteSalaAsync(codigoSala);
        }
        
        public bool EsSalaDisponible(string codigoSala) {
            return base.Channel.EsSalaDisponible(codigoSala);
        }
        
        public System.Threading.Tasks.Task<bool> EsSalaDisponibleAsync(string codigoSala) {
            return base.Channel.EsSalaDisponibleAsync(codigoSala);
        }
        
        public void CambiarVentanaParaTodos(string codigoSala) {
            base.Channel.CambiarVentanaParaTodos(codigoSala);
        }
        
        public System.Threading.Tasks.Task CambiarVentanaParaTodosAsync(string codigoSala) {
            return base.Channel.CambiarVentanaParaTodosAsync(codigoSala);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Servidor.IGestionAmigos")]
    public interface IGestionAmigos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionAmigos/EnviarSolicitudAmistad", ReplyAction="http://tempuri.org/IGestionAmigos/EnviarSolicitudAmistadResponse")]
        DobbleGame.Servidor.RespuestaServicioOfboolean EnviarSolicitudAmistad(int idUsuarioPrincipal, string nombreUsuarioAmigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionAmigos/EnviarSolicitudAmistad", ReplyAction="http://tempuri.org/IGestionAmigos/EnviarSolicitudAmistadResponse")]
        System.Threading.Tasks.Task<DobbleGame.Servidor.RespuestaServicioOfboolean> EnviarSolicitudAmistadAsync(int idUsuarioPrincipal, string nombreUsuarioAmigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionAmigos/AmistadYaExiste", ReplyAction="http://tempuri.org/IGestionAmigos/AmistadYaExisteResponse")]
        DobbleGame.Servidor.RespuestaServicioOfboolean AmistadYaExiste(int idUsuarioPrincipal, string nombreUsuarioAmigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionAmigos/AmistadYaExiste", ReplyAction="http://tempuri.org/IGestionAmigos/AmistadYaExisteResponse")]
        System.Threading.Tasks.Task<DobbleGame.Servidor.RespuestaServicioOfboolean> AmistadYaExisteAsync(int idUsuarioPrincipal, string nombreUsuarioAmigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionAmigos/ObtenerSolicitudesPendientes", ReplyAction="http://tempuri.org/IGestionAmigos/ObtenerSolicitudesPendientesResponse")]
        DobbleGame.Servidor.RespuestaServicioOfArrayOfAmistad6jbaXeYD ObtenerSolicitudesPendientes(int idUsuarioAmigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionAmigos/ObtenerSolicitudesPendientes", ReplyAction="http://tempuri.org/IGestionAmigos/ObtenerSolicitudesPendientesResponse")]
        System.Threading.Tasks.Task<DobbleGame.Servidor.RespuestaServicioOfArrayOfAmistad6jbaXeYD> ObtenerSolicitudesPendientesAsync(int idUsuarioAmigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionAmigos/ObtenerUsuario", ReplyAction="http://tempuri.org/IGestionAmigos/ObtenerUsuarioResponse")]
        DobbleGame.Servidor.RespuestaServicioOfCuentaUsuario6jbaXeYD ObtenerUsuario(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionAmigos/ObtenerUsuario", ReplyAction="http://tempuri.org/IGestionAmigos/ObtenerUsuarioResponse")]
        System.Threading.Tasks.Task<DobbleGame.Servidor.RespuestaServicioOfCuentaUsuario6jbaXeYD> ObtenerUsuarioAsync(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionAmigos/AceptarSolicitud", ReplyAction="http://tempuri.org/IGestionAmigos/AceptarSolicitudResponse")]
        DobbleGame.Servidor.RespuestaServicioOfboolean AceptarSolicitud(int idAmistad, string nombreUsuarioAmigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionAmigos/AceptarSolicitud", ReplyAction="http://tempuri.org/IGestionAmigos/AceptarSolicitudResponse")]
        System.Threading.Tasks.Task<DobbleGame.Servidor.RespuestaServicioOfboolean> AceptarSolicitudAsync(int idAmistad, string nombreUsuarioAmigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionAmigos/EliminarAmistad", ReplyAction="http://tempuri.org/IGestionAmigos/EliminarAmistadResponse")]
        DobbleGame.Servidor.RespuestaServicioOfboolean EliminarAmistad(int idAmistad, string nombreUsuario, string nombreUsuarioAmigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionAmigos/EliminarAmistad", ReplyAction="http://tempuri.org/IGestionAmigos/EliminarAmistadResponse")]
        System.Threading.Tasks.Task<DobbleGame.Servidor.RespuestaServicioOfboolean> EliminarAmistadAsync(int idAmistad, string nombreUsuario, string nombreUsuarioAmigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionAmigos/ObtenerAmistades", ReplyAction="http://tempuri.org/IGestionAmigos/ObtenerAmistadesResponse")]
        DobbleGame.Servidor.RespuestaServicioOfArrayOfAmistad6jbaXeYD ObtenerAmistades(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionAmigos/ObtenerAmistades", ReplyAction="http://tempuri.org/IGestionAmigos/ObtenerAmistadesResponse")]
        System.Threading.Tasks.Task<DobbleGame.Servidor.RespuestaServicioOfArrayOfAmistad6jbaXeYD> ObtenerAmistadesAsync(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionAmigos/ObtenerAmistad", ReplyAction="http://tempuri.org/IGestionAmigos/ObtenerAmistadResponse")]
        DobbleGame.Servidor.RespuestaServicioOfAmistad6jbaXeYD ObtenerAmistad(int idAmistad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionAmigos/ObtenerAmistad", ReplyAction="http://tempuri.org/IGestionAmigos/ObtenerAmistadResponse")]
        System.Threading.Tasks.Task<DobbleGame.Servidor.RespuestaServicioOfAmistad6jbaXeYD> ObtenerAmistadAsync(int idAmistad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionAmigos/ObtenerSolicitud", ReplyAction="http://tempuri.org/IGestionAmigos/ObtenerSolicitudResponse")]
        DobbleGame.Servidor.RespuestaServicioOfAmistad6jbaXeYD ObtenerSolicitud();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionAmigos/ObtenerSolicitud", ReplyAction="http://tempuri.org/IGestionAmigos/ObtenerSolicitudResponse")]
        System.Threading.Tasks.Task<DobbleGame.Servidor.RespuestaServicioOfAmistad6jbaXeYD> ObtenerSolicitudAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionAmigos/AgregarUsuario", ReplyAction="http://tempuri.org/IGestionAmigos/AgregarUsuarioResponse")]
        void AgregarUsuario(string nombreUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionAmigos/AgregarUsuario", ReplyAction="http://tempuri.org/IGestionAmigos/AgregarUsuarioResponse")]
        System.Threading.Tasks.Task AgregarUsuarioAsync(string nombreUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionAmigos/QuitarUsuario", ReplyAction="http://tempuri.org/IGestionAmigos/QuitarUsuarioResponse")]
        void QuitarUsuario(string nombreUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionAmigos/QuitarUsuario", ReplyAction="http://tempuri.org/IGestionAmigos/QuitarUsuarioResponse")]
        System.Threading.Tasks.Task QuitarUsuarioAsync(string nombreUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionAmigos/ObtenerUsuarioConectado", ReplyAction="http://tempuri.org/IGestionAmigos/ObtenerUsuarioConectadoResponse")]
        bool ObtenerUsuarioConectado(string nombreUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionAmigos/ObtenerUsuarioConectado", ReplyAction="http://tempuri.org/IGestionAmigos/ObtenerUsuarioConectadoResponse")]
        System.Threading.Tasks.Task<bool> ObtenerUsuarioConectadoAsync(string nombreUsuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGestionAmigosChannel : DobbleGame.Servidor.IGestionAmigos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GestionAmigosClient : System.ServiceModel.ClientBase<DobbleGame.Servidor.IGestionAmigos>, DobbleGame.Servidor.IGestionAmigos {
        
        public GestionAmigosClient() {
        }
        
        public GestionAmigosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GestionAmigosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestionAmigosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestionAmigosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DobbleGame.Servidor.RespuestaServicioOfboolean EnviarSolicitudAmistad(int idUsuarioPrincipal, string nombreUsuarioAmigo) {
            return base.Channel.EnviarSolicitudAmistad(idUsuarioPrincipal, nombreUsuarioAmigo);
        }
        
        public System.Threading.Tasks.Task<DobbleGame.Servidor.RespuestaServicioOfboolean> EnviarSolicitudAmistadAsync(int idUsuarioPrincipal, string nombreUsuarioAmigo) {
            return base.Channel.EnviarSolicitudAmistadAsync(idUsuarioPrincipal, nombreUsuarioAmigo);
        }
        
        public DobbleGame.Servidor.RespuestaServicioOfboolean AmistadYaExiste(int idUsuarioPrincipal, string nombreUsuarioAmigo) {
            return base.Channel.AmistadYaExiste(idUsuarioPrincipal, nombreUsuarioAmigo);
        }
        
        public System.Threading.Tasks.Task<DobbleGame.Servidor.RespuestaServicioOfboolean> AmistadYaExisteAsync(int idUsuarioPrincipal, string nombreUsuarioAmigo) {
            return base.Channel.AmistadYaExisteAsync(idUsuarioPrincipal, nombreUsuarioAmigo);
        }
        
        public DobbleGame.Servidor.RespuestaServicioOfArrayOfAmistad6jbaXeYD ObtenerSolicitudesPendientes(int idUsuarioAmigo) {
            return base.Channel.ObtenerSolicitudesPendientes(idUsuarioAmigo);
        }
        
        public System.Threading.Tasks.Task<DobbleGame.Servidor.RespuestaServicioOfArrayOfAmistad6jbaXeYD> ObtenerSolicitudesPendientesAsync(int idUsuarioAmigo) {
            return base.Channel.ObtenerSolicitudesPendientesAsync(idUsuarioAmigo);
        }
        
        public DobbleGame.Servidor.RespuestaServicioOfCuentaUsuario6jbaXeYD ObtenerUsuario(int idUsuario) {
            return base.Channel.ObtenerUsuario(idUsuario);
        }
        
        public System.Threading.Tasks.Task<DobbleGame.Servidor.RespuestaServicioOfCuentaUsuario6jbaXeYD> ObtenerUsuarioAsync(int idUsuario) {
            return base.Channel.ObtenerUsuarioAsync(idUsuario);
        }
        
        public DobbleGame.Servidor.RespuestaServicioOfboolean AceptarSolicitud(int idAmistad, string nombreUsuarioAmigo) {
            return base.Channel.AceptarSolicitud(idAmistad, nombreUsuarioAmigo);
        }
        
        public System.Threading.Tasks.Task<DobbleGame.Servidor.RespuestaServicioOfboolean> AceptarSolicitudAsync(int idAmistad, string nombreUsuarioAmigo) {
            return base.Channel.AceptarSolicitudAsync(idAmistad, nombreUsuarioAmigo);
        }
        
        public DobbleGame.Servidor.RespuestaServicioOfboolean EliminarAmistad(int idAmistad, string nombreUsuario, string nombreUsuarioAmigo) {
            return base.Channel.EliminarAmistad(idAmistad, nombreUsuario, nombreUsuarioAmigo);
        }
        
        public System.Threading.Tasks.Task<DobbleGame.Servidor.RespuestaServicioOfboolean> EliminarAmistadAsync(int idAmistad, string nombreUsuario, string nombreUsuarioAmigo) {
            return base.Channel.EliminarAmistadAsync(idAmistad, nombreUsuario, nombreUsuarioAmigo);
        }
        
        public DobbleGame.Servidor.RespuestaServicioOfArrayOfAmistad6jbaXeYD ObtenerAmistades(int idUsuario) {
            return base.Channel.ObtenerAmistades(idUsuario);
        }
        
        public System.Threading.Tasks.Task<DobbleGame.Servidor.RespuestaServicioOfArrayOfAmistad6jbaXeYD> ObtenerAmistadesAsync(int idUsuario) {
            return base.Channel.ObtenerAmistadesAsync(idUsuario);
        }
        
        public DobbleGame.Servidor.RespuestaServicioOfAmistad6jbaXeYD ObtenerAmistad(int idAmistad) {
            return base.Channel.ObtenerAmistad(idAmistad);
        }
        
        public System.Threading.Tasks.Task<DobbleGame.Servidor.RespuestaServicioOfAmistad6jbaXeYD> ObtenerAmistadAsync(int idAmistad) {
            return base.Channel.ObtenerAmistadAsync(idAmistad);
        }
        
        public DobbleGame.Servidor.RespuestaServicioOfAmistad6jbaXeYD ObtenerSolicitud() {
            return base.Channel.ObtenerSolicitud();
        }
        
        public System.Threading.Tasks.Task<DobbleGame.Servidor.RespuestaServicioOfAmistad6jbaXeYD> ObtenerSolicitudAsync() {
            return base.Channel.ObtenerSolicitudAsync();
        }
        
        public void AgregarUsuario(string nombreUsuario) {
            base.Channel.AgregarUsuario(nombreUsuario);
        }
        
        public System.Threading.Tasks.Task AgregarUsuarioAsync(string nombreUsuario) {
            return base.Channel.AgregarUsuarioAsync(nombreUsuario);
        }
        
        public void QuitarUsuario(string nombreUsuario) {
            base.Channel.QuitarUsuario(nombreUsuario);
        }
        
        public System.Threading.Tasks.Task QuitarUsuarioAsync(string nombreUsuario) {
            return base.Channel.QuitarUsuarioAsync(nombreUsuario);
        }
        
        public bool ObtenerUsuarioConectado(string nombreUsuario) {
            return base.Channel.ObtenerUsuarioConectado(nombreUsuario);
        }
        
        public System.Threading.Tasks.Task<bool> ObtenerUsuarioConectadoAsync(string nombreUsuario) {
            return base.Channel.ObtenerUsuarioConectadoAsync(nombreUsuario);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Servidor.IGestionNotificacionesAmigos", CallbackContract=typeof(DobbleGame.Servidor.IGestionNotificacionesAmigosCallback))]
    public interface IGestionNotificacionesAmigos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionNotificacionesAmigos/ConectarCliente", ReplyAction="http://tempuri.org/IGestionNotificacionesAmigos/ConectarClienteResponse")]
        void ConectarCliente(string nombreUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionNotificacionesAmigos/ConectarCliente", ReplyAction="http://tempuri.org/IGestionNotificacionesAmigos/ConectarClienteResponse")]
        System.Threading.Tasks.Task ConectarClienteAsync(string nombreUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionNotificacionesAmigos/DesconectarCliente", ReplyAction="http://tempuri.org/IGestionNotificacionesAmigos/DesconectarClienteResponse")]
        void DesconectarCliente(string nombreUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionNotificacionesAmigos/DesconectarCliente", ReplyAction="http://tempuri.org/IGestionNotificacionesAmigos/DesconectarClienteResponse")]
        System.Threading.Tasks.Task DesconectarClienteAsync(string nombreUsuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGestionNotificacionesAmigosCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGestionNotificacionesAmigos/NotificarSolicitudAmistad")]
        void NotificarSolicitudAmistad();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGestionNotificacionesAmigos/NotificarCambio")]
        void NotificarCambio();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGestionNotificacionesAmigosChannel : DobbleGame.Servidor.IGestionNotificacionesAmigos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GestionNotificacionesAmigosClient : System.ServiceModel.DuplexClientBase<DobbleGame.Servidor.IGestionNotificacionesAmigos>, DobbleGame.Servidor.IGestionNotificacionesAmigos {
        
        public GestionNotificacionesAmigosClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public GestionNotificacionesAmigosClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public GestionNotificacionesAmigosClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public GestionNotificacionesAmigosClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public GestionNotificacionesAmigosClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void ConectarCliente(string nombreUsuario) {
            base.Channel.ConectarCliente(nombreUsuario);
        }
        
        public System.Threading.Tasks.Task ConectarClienteAsync(string nombreUsuario) {
            return base.Channel.ConectarClienteAsync(nombreUsuario);
        }
        
        public void DesconectarCliente(string nombreUsuario) {
            base.Channel.DesconectarCliente(nombreUsuario);
        }
        
        public System.Threading.Tasks.Task DesconectarClienteAsync(string nombreUsuario) {
            return base.Channel.DesconectarClienteAsync(nombreUsuario);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Servidor.IGestionPartida", CallbackContract=typeof(DobbleGame.Servidor.IGestionPartidaCallback))]
    public interface IGestionPartida {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionPartida/CrearNuevaPartida", ReplyAction="http://tempuri.org/IGestionPartida/CrearNuevaPartidaResponse")]
        bool CrearNuevaPartida(string codigoSala);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionPartida/CrearNuevaPartida", ReplyAction="http://tempuri.org/IGestionPartida/CrearNuevaPartidaResponse")]
        System.Threading.Tasks.Task<bool> CrearNuevaPartidaAsync(string codigoSala);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGestionPartida/UnirJugadorAPartida")]
        void UnirJugadorAPartida(string nombreUsuario, string codigoSala);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGestionPartida/UnirJugadorAPartida")]
        System.Threading.Tasks.Task UnirJugadorAPartidaAsync(string nombreUsuario, string codigoSala);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionPartida/AbandonarPartida", ReplyAction="http://tempuri.org/IGestionPartida/AbandonarPartidaResponse")]
        bool AbandonarPartida(string nombreUsuario, string codigoSala);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionPartida/AbandonarPartida", ReplyAction="http://tempuri.org/IGestionPartida/AbandonarPartidaResponse")]
        System.Threading.Tasks.Task<bool> AbandonarPartidaAsync(string nombreUsuario, string codigoSala);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGestionPartida/NotificarActualizacionDeJugadoresEnPartida")]
        void NotificarActualizacionDeJugadoresEnPartida(string codigoSala);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGestionPartida/NotificarActualizacionDeJugadoresEnPartida")]
        System.Threading.Tasks.Task NotificarActualizacionDeJugadoresEnPartidaAsync(string codigoSala);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGestionPartida/NotificarInicioPartida")]
        void NotificarInicioPartida(string codigoSala);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGestionPartida/NotificarInicioPartida")]
        System.Threading.Tasks.Task NotificarInicioPartidaAsync(string codigoSala);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGestionPartida/NotificarDistribucionCartas")]
        void NotificarDistribucionCartas(string codigoSala);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGestionPartida/NotificarDistribucionCartas")]
        System.Threading.Tasks.Task NotificarDistribucionCartasAsync(string codigoSala);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGestionPartida/ValidarCarta")]
        void ValidarCarta(string nombreUsuario, string rutaIcono, string codigoSala);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGestionPartida/ValidarCarta")]
        System.Threading.Tasks.Task ValidarCartaAsync(string nombreUsuario, string rutaIcono, string codigoSala);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGestionPartidaCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGestionPartida/ActualizarJugadoresEnPartida")]
        void ActualizarJugadoresEnPartida(DobbleGame.Servidor.Jugador[] jugadoresConectados);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGestionPartida/IniciarPartida")]
        void IniciarPartida();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGestionPartida/FinalizarPartida")]
        void FinalizarPartida();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGestionPartida/AsignarCarta")]
        void AsignarCarta(DobbleGame.Servidor.Carta carta);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGestionPartida/AsignarCartaCentral")]
        void AsignarCartaCentral(DobbleGame.Servidor.Carta cartaCentral);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IGestionPartida/ActualizarPuntosEnPartida")]
        void ActualizarPuntosEnPartida(string nombreUsuario, int puntosEnPartida);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGestionPartidaChannel : DobbleGame.Servidor.IGestionPartida, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GestionPartidaClient : System.ServiceModel.DuplexClientBase<DobbleGame.Servidor.IGestionPartida>, DobbleGame.Servidor.IGestionPartida {
        
        public GestionPartidaClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public GestionPartidaClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public GestionPartidaClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public GestionPartidaClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public GestionPartidaClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public bool CrearNuevaPartida(string codigoSala) {
            return base.Channel.CrearNuevaPartida(codigoSala);
        }
        
        public System.Threading.Tasks.Task<bool> CrearNuevaPartidaAsync(string codigoSala) {
            return base.Channel.CrearNuevaPartidaAsync(codigoSala);
        }
        
        public void UnirJugadorAPartida(string nombreUsuario, string codigoSala) {
            base.Channel.UnirJugadorAPartida(nombreUsuario, codigoSala);
        }
        
        public System.Threading.Tasks.Task UnirJugadorAPartidaAsync(string nombreUsuario, string codigoSala) {
            return base.Channel.UnirJugadorAPartidaAsync(nombreUsuario, codigoSala);
        }
        
        public bool AbandonarPartida(string nombreUsuario, string codigoSala) {
            return base.Channel.AbandonarPartida(nombreUsuario, codigoSala);
        }
        
        public System.Threading.Tasks.Task<bool> AbandonarPartidaAsync(string nombreUsuario, string codigoSala) {
            return base.Channel.AbandonarPartidaAsync(nombreUsuario, codigoSala);
        }
        
        public void NotificarActualizacionDeJugadoresEnPartida(string codigoSala) {
            base.Channel.NotificarActualizacionDeJugadoresEnPartida(codigoSala);
        }
        
        public System.Threading.Tasks.Task NotificarActualizacionDeJugadoresEnPartidaAsync(string codigoSala) {
            return base.Channel.NotificarActualizacionDeJugadoresEnPartidaAsync(codigoSala);
        }
        
        public void NotificarInicioPartida(string codigoSala) {
            base.Channel.NotificarInicioPartida(codigoSala);
        }
        
        public System.Threading.Tasks.Task NotificarInicioPartidaAsync(string codigoSala) {
            return base.Channel.NotificarInicioPartidaAsync(codigoSala);
        }
        
        public void NotificarDistribucionCartas(string codigoSala) {
            base.Channel.NotificarDistribucionCartas(codigoSala);
        }
        
        public System.Threading.Tasks.Task NotificarDistribucionCartasAsync(string codigoSala) {
            return base.Channel.NotificarDistribucionCartasAsync(codigoSala);
        }
        
        public void ValidarCarta(string nombreUsuario, string rutaIcono, string codigoSala) {
            base.Channel.ValidarCarta(nombreUsuario, rutaIcono, codigoSala);
        }
        
        public System.Threading.Tasks.Task ValidarCartaAsync(string nombreUsuario, string rutaIcono, string codigoSala) {
            return base.Channel.ValidarCartaAsync(nombreUsuario, rutaIcono, codigoSala);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Servidor.IGestionCorreos")]
    public interface IGestionCorreos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionCorreos/EnviarCodigo", ReplyAction="http://tempuri.org/IGestionCorreos/EnviarCodigoResponse")]
        DobbleGame.Servidor.RespuestaServicioOfboolean EnviarCodigo(string correo, string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestionCorreos/EnviarCodigo", ReplyAction="http://tempuri.org/IGestionCorreos/EnviarCodigoResponse")]
        System.Threading.Tasks.Task<DobbleGame.Servidor.RespuestaServicioOfboolean> EnviarCodigoAsync(string correo, string codigo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGestionCorreosChannel : DobbleGame.Servidor.IGestionCorreos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GestionCorreosClient : System.ServiceModel.ClientBase<DobbleGame.Servidor.IGestionCorreos>, DobbleGame.Servidor.IGestionCorreos {
        
        public GestionCorreosClient() {
        }
        
        public GestionCorreosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GestionCorreosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestionCorreosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GestionCorreosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DobbleGame.Servidor.RespuestaServicioOfboolean EnviarCodigo(string correo, string codigo) {
            return base.Channel.EnviarCodigo(correo, codigo);
        }
        
        public System.Threading.Tasks.Task<DobbleGame.Servidor.RespuestaServicioOfboolean> EnviarCodigoAsync(string correo, string codigo) {
            return base.Channel.EnviarCodigoAsync(correo, codigo);
        }
    }
}
