//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DobbleGame.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DobbleGame.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Abandonar.
        /// </summary>
        public static string btn_Abandonar {
            get {
                return ResourceManager.GetString("btn_Abandonar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar foto.
        /// </summary>
        public static string btn_ActualizarFoto {
            get {
                return ResourceManager.GetString("btn_ActualizarFoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Agregar amistad.
        /// </summary>
        public static string btn_AgregarAmistad {
            get {
                return ResourceManager.GetString("btn_AgregarAmistad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar a Inglés.
        /// </summary>
        public static string btn_CambioIdioma {
            get {
                return ResourceManager.GetString("btn_CambioIdioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar sesión.
        /// </summary>
        public static string btn_CerrarSesión {
            get {
                return ResourceManager.GetString("btn_CerrarSesión", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Sala.
        /// </summary>
        public static string btn_CrearSala {
            get {
                return ResourceManager.GetString("btn_CrearSala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        public static string btn_Eliminar {
            get {
                return ResourceManager.GetString("btn_Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar amigo.
        /// </summary>
        public static string btn_EliminarAmigo {
            get {
                return ResourceManager.GetString("btn_EliminarAmigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entrar.
        /// </summary>
        public static string btn_Entrar {
            get {
                return ResourceManager.GetString("btn_Entrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entrar como invitado.
        /// </summary>
        public static string btn_EntrarComoInvitado {
            get {
                return ResourceManager.GetString("btn_EntrarComoInvitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar.
        /// </summary>
        public static string btn_Enviar {
            get {
                return ResourceManager.GetString("btn_Enviar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar código.
        /// </summary>
        public static string btn_EnviarCódigo {
            get {
                return ResourceManager.GetString("btn_EnviarCódigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Expulsar.
        /// </summary>
        public static string btn_Expulsar {
            get {
                return ResourceManager.GetString("btn_Expulsar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar partida.
        /// </summary>
        public static string btn_IniciarPartida {
            get {
                return ResourceManager.GetString("btn_IniciarPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitar.
        /// </summary>
        public static string btn_Invitar {
            get {
                return ResourceManager.GetString("btn_Invitar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitar por correo.
        /// </summary>
        public static string btn_InvitarPorCorreo {
            get {
                return ResourceManager.GetString("btn_InvitarPorCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ir a la sala.
        /// </summary>
        public static string btn_IrASala {
            get {
                return ResourceManager.GetString("btn_IrASala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ir a la pantalla de inicio de sesión .
        /// </summary>
        public static string btn_IrInicioSesion_ {
            get {
                return ResourceManager.GetString("btn_IrInicioSesion ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Listo.
        /// </summary>
        public static string btn_Listo {
            get {
                return ResourceManager.GetString("btn_Listo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rechazar.
        /// </summary>
        public static string btn_Rechazar {
            get {
                return ResourceManager.GetString("btn_Rechazar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar.
        /// </summary>
        public static string btn_Registrar {
            get {
                return ResourceManager.GetString("btn_Registrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reintentar.
        /// </summary>
        public static string btn_Reintentar {
            get {
                return ResourceManager.GetString("btn_Reintentar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitudes de amistad.
        /// </summary>
        public static string btn_SolicitudesDeAmistad {
            get {
                return ResourceManager.GetString("btn_SolicitudesDeAmistad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unirse.
        /// </summary>
        public static string btn_Unirse {
            get {
                return ResourceManager.GetString("btn_Unirse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unirse a sala.
        /// </summary>
        public static string btn_UnirseASala {
            get {
                return ResourceManager.GetString("btn_UnirseASala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        public static string global_Aceptar {
            get {
                return ResourceManager.GetString("global_Aceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar.
        /// </summary>
        public static string global_Actualizar {
            get {
                return ResourceManager.GetString("global_Actualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string global_Cancelar {
            get {
                return ResourceManager.GetString("global_Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar contraseña.
        /// </summary>
        public static string global_ConfirmarContraseña {
            get {
                return ResourceManager.GetString("global_ConfirmarContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico.
        /// </summary>
        public static string global_CorreoElectrónico {
            get {
                return ResourceManager.GetString("global_CorreoElectrónico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar sesión.
        /// </summary>
        public static string global_IniciarSesión {
            get {
                return ResourceManager.GetString("global_IniciarSesión", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Listo!.
        /// </summary>
        public static string global_Listo {
            get {
                return ResourceManager.GetString("global_Listo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puedes tener la misma contraseña .
        /// </summary>
        public static string global_MismaContraseña_ {
            get {
                return ResourceManager.GetString("global_MismaContraseña ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva contraseña.
        /// </summary>
        public static string global_NuevaContraseña {
            get {
                return ResourceManager.GetString("global_NuevaContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ok.
        /// </summary>
        public static string global_Ok {
            get {
                return ResourceManager.GetString("global_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        public static string global_Usuario {
            get {
                return ResourceManager.GetString("global_Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ausente.
        /// </summary>
        public static string lb_Ausente {
            get {
                return ResourceManager.GetString("lb_Ausente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        public static string lb_Buscar {
            get {
                return ResourceManager.GetString("lb_Buscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambio de contraseña.
        /// </summary>
        public static string lb_CambioContraseña {
            get {
                return ResourceManager.GetString("lb_CambioContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambio de nombre.
        /// </summary>
        public static string lb_CambioNombre {
            get {
                return ResourceManager.GetString("lb_CambioNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El formulario contiene campos vacíos.
        /// </summary>
        public static string lb_CamposVacíos {
            get {
                return ResourceManager.GetString("lb_CamposVacíos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cartas restantes {0}.
        /// </summary>
        public static string lb_CartasRestantes {
            get {
                return ResourceManager.GetString("lb_CartasRestantes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hemos enviado un código a la dirección de correo electrónico.
        /// </summary>
        public static string lb_CódigoEnviado {
            get {
                return ResourceManager.GetString("lb_CódigoEnviado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código invalido.
        /// </summary>
        public static string lb_CodigoInvalido {
            get {
                return ResourceManager.GetString("lb_CodigoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hacer esto te hará abandonar la sala  
        ///¿Seguro que deseas ir al perfil?.
        /// </summary>
        public static string lb_ConfirmarIrPerfil {
            get {
                return ResourceManager.GetString("lb_ConfirmarIrPerfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string lb_Contraseña {
            get {
                return ResourceManager.GetString("lb_Contraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña actual.
        /// </summary>
        public static string lb_ContraseñaActual {
            get {
                return ResourceManager.GetString("lb_ContraseñaActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña actual no es valida .
        /// </summary>
        public static string lb_ContraseñaActualInvalida {
            get {
                return ResourceManager.GetString("lb_ContraseñaActualInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña no cumple con lo solicitado .
        /// </summary>
        public static string lb_ContraseñaIncorrecta {
            get {
                return ResourceManager.GetString("lb_ContraseñaIncorrecta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las contraseñas no coinciden.
        /// </summary>
        public static string lb_ContraseñaNoCoincide {
            get {
                return ResourceManager.GetString("lb_ContraseñaNoCoincide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Olvidaste tu contraseña?.
        /// </summary>
        public static string lb_ContraseñaOlvidada {
            get {
                return ResourceManager.GetString("lb_ContraseñaOlvidada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo electrónico ya existe.
        /// </summary>
        public static string lb_CorreoExistente {
            get {
                return ResourceManager.GetString("lb_CorreoExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo no es válido.
        /// </summary>
        public static string lb_CorreoInválido {
            get {
                return ResourceManager.GetString("lb_CorreoInválido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El correo es inexistente .
        /// </summary>
        public static string lb_CorreoNoExiste_ {
            get {
                return ResourceManager.GetString("lb_CorreoNoExiste ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Aún no has creado una cuenta? Registrate.
        /// </summary>
        public static string lb_CrearCuenta {
            get {
                return ResourceManager.GetString("lb_CrearCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El formulario contiene datos inválidos.
        /// </summary>
        public static string lb_DatosInválidos {
            get {
                return ResourceManager.GetString("lb_DatosInválidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Dobble!.
        /// </summary>
        public static string lb_Dobble {
            get {
                return ResourceManager.GetString("lb_Dobble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a DOBBLE.NET.
        /// </summary>
        public static string lb_Dobble_NET {
            get {
                return ResourceManager.GetString("lb_Dobble.NET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Seguro que deseas eliminar a este amigo? .
        /// </summary>
        public static string lb_EliminarAmigo {
            get {
                return ResourceManager.GetString("lb_EliminarAmigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Empate!.
        /// </summary>
        public static string lb_Empate {
            get {
                return ResourceManager.GetString("lb_Empate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En línea.
        /// </summary>
        public static string lb_EnLínea {
            get {
                return ResourceManager.GetString("lb_EnLínea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar invitación.
        /// </summary>
        public static string lb_EnviarInvitación {
            get {
                return ResourceManager.GetString("lb_EnviarInvitación", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar solicitud de amistad .
        /// </summary>
        public static string lb_EnviarSolicitud_ {
            get {
                return ResourceManager.GetString("lb_EnviarSolicitud ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Envío de código.
        /// </summary>
        public static string lb_EnvíoDeCódigo {
            get {
                return ResourceManager.GetString("lb_EnvíoDeCódigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de conexión con la base de datos.
        /// </summary>
        public static string lb_ErrorConexiónBD {
            get {
                return ResourceManager.GetString("lb_ErrorConexiónBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de conexión con el servidor.
        /// </summary>
        public static string lb_ErrorConexiónServidor {
            get {
                return ResourceManager.GetString("lb_ErrorConexiónServidor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un error inesperado .
        /// </summary>
        public static string lb_ErrorInesperado {
            get {
                return ResourceManager.GetString("lb_ErrorInesperado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario y/o contraseña son incorrectos.
        /// </summary>
        public static string lb_ErrorInicioSesión {
            get {
                return ResourceManager.GetString("lb_ErrorInicioSesión", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Estás listo?.
        /// </summary>
        public static string lb_EstasListo {
            get {
                return ResourceManager.GetString("lb_EstasListo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Fin del juego!.
        /// </summary>
        public static string lb_FinDelJuego {
            get {
                return ResourceManager.GetString("lb_FinDelJuego", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El archivo es invalido o es demasiado grande, selecciona una que no supere los 10 kb .
        /// </summary>
        public static string lb_FormatoInválido {
            get {
                return ResourceManager.GetString("lb_FormatoInválido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Has sido expulsado de la sala.
        /// </summary>
        public static string lb_HasSidoExpulsado {
            get {
                return ResourceManager.GetString("lb_HasSidoExpulsado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresar código.
        /// </summary>
        public static string lb_IngresarCódigo {
            get {
                return ResourceManager.GetString("lb_IngresarCódigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresa el nombre de usuario del jugador .
        /// </summary>
        public static string lb_IngresarNombreJugador_ {
            get {
                return ResourceManager.GetString("lb_IngresarNombreJugador ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese su nuevo nombre de usuario.
        /// </summary>
        public static string lb_IngresarNombreUsuario {
            get {
                return ResourceManager.GetString("lb_IngresarNombreUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese su nuevo nombre de usuario.
        /// </summary>
        public static string lb_IngreseNuevoNombre {
            get {
                return ResourceManager.GetString("lb_IngreseNuevoNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitado{0}.
        /// </summary>
        public static string lb_Invitado {
            get {
                return ResourceManager.GetString("lb_Invitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugador {0}.
        /// </summary>
        public static string lb_Jugador {
            get {
                return ResourceManager.GetString("lb_Jugador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Seguro que deseas abandonar la partida?.
        /// </summary>
        public static string lb_MensajeAbandonarPartida {
            get {
                return ResourceManager.GetString("lb_MensajeAbandonarPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Seguro que deseas cerrar sesión?.
        /// </summary>
        public static string lb_MensajeCerrarSesion {
            get {
                return ResourceManager.GetString("lb_MensajeCerrarSesion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Seguro que deseas eliminar a ...?.
        /// </summary>
        public static string lb_MensajeEliminarAmigo {
            get {
                return ResourceManager.GetString("lb_MensajeEliminarAmigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese el correo electrónico para enviar la invitación a la sala.
        /// </summary>
        public static string lb_MensajeEnviarInvitación {
            get {
                return ResourceManager.GetString("lb_MensajeEnviarInvitación", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lo sentimos, parece que el cliente no se encuentra en el canal actual del servidor, por favor, vuelve a iniciar sesión. .
        /// </summary>
        public static string lb_MensajeErrorCanalServidor {
            get {
                return ResourceManager.GetString("lb_MensajeErrorCanalServidor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lb_MensajeErrorCanalServidor_ {
            get {
                return ResourceManager.GetString("lb_MensajeErrorCanalServidor ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lo sentimos, parece que hemos perdido la conexión con la base de datos, favor de intentarlo más tarde.
        /// </summary>
        public static string lb_MensajeErrorConexiónBD {
            get {
                return ResourceManager.GetString("lb_MensajeErrorConexiónBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lo sentimos, parece que hemos perdido la conexión al servidor, favor de intentarlo más tarde.
        /// </summary>
        public static string lb_MensajeErrorConexiónServidor {
            get {
                return ResourceManager.GetString("lb_MensajeErrorConexiónServidor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Seguro que deseas expulsar a {0}?.
        /// </summary>
        public static string lb_MensajeExpulsarJugador {
            get {
                return ResourceManager.GetString("lb_MensajeExpulsarJugador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciaste como invitado, para comprobar todas las funciones de DOBBLE.NET inicia sesión.
        /// </summary>
        public static string lb_MensajeMenúInvitado {
            get {
                return ResourceManager.GetString("lb_MensajeMenúInvitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese el código de sala para unirse.
        /// </summary>
        public static string lb_MensajeUnirsePartida {
            get {
                return ResourceManager.GetString("lb_MensajeUnirsePartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de usuario.
        /// </summary>
        public static string lb_NombreUsuario {
            get {
                return ResourceManager.GetString("lb_NombreUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo nombre de usuario.
        /// </summary>
        public static string lb_NuevoNombreUsuario {
            get {
                return ResourceManager.GetString("lb_NuevoNombreUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puntaje: {0}.
        /// </summary>
        public static string lb_Puntaje {
            get {
                return ResourceManager.GetString("lb_Puntaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puntos: {0}.
        /// </summary>
        public static string lb_Puntos {
            get {
                return ResourceManager.GetString("lb_Puntos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} puntos.
        /// </summary>
        public static string lb_PuntosEnJuego {
            get {
                return ResourceManager.GetString("lb_PuntosEnJuego", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro.
        /// </summary>
        public static string lb_Registro {
            get {
                return ResourceManager.GetString("lb_Registro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro realizado con éxito.
        /// </summary>
        public static string lb_RegistroExitoso {
            get {
                return ResourceManager.GetString("lb_RegistroExitoso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La sala se encuentra en partida.
        /// </summary>
        public static string lb_SalaEnPartida {
            get {
                return ResourceManager.GetString("lb_SalaEnPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No existe la sala.
        /// </summary>
        public static string lb_SalaInexistente {
            get {
                return ResourceManager.GetString("lb_SalaInexistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La sala está llena.
        /// </summary>
        public static string lb_SalaLlena {
            get {
                return ResourceManager.GetString("lb_SalaLlena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La cuenta ya tiene una sesión activa.
        /// </summary>
        public static string lb_SesiónActiva {
            get {
                return ResourceManager.GetString("lb_SesiónActiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No puedes mandar una solicitud de amistad a ti mismo .
        /// </summary>
        public static string lb_SolicitudATiMismo_ {
            get {
                return ResourceManager.GetString("lb_SolicitudATiMismo ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitudes de amistad.
        /// </summary>
        public static string lb_SolicitudesAmistad {
            get {
                return ResourceManager.GetString("lb_SolicitudesAmistad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya hay una solicitud pendiente o una amistad con este usuario .
        /// </summary>
        public static string lb_SolicitudYaEnviada_ {
            get {
                return ResourceManager.GetString("lb_SolicitudYaEnviada ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡{0} te está invitando a jugar! .
        /// </summary>
        public static string lb_TeEstaInvitando_ {
            get {
                return ResourceManager.GetString("lb_TeEstaInvitando ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unirse a partida.
        /// </summary>
        public static string lb_UnirseAPartida {
            get {
                return ResourceManager.GetString("lb_UnirseAPartida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre de usuario ya existe.
        /// </summary>
        public static string lb_UsuarioExistente {
            get {
                return ResourceManager.GetString("lb_UsuarioExistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre de usuario no existe.
        /// </summary>
        public static string lb_UsuarioInexistente {
            get {
                return ResourceManager.GetString("lb_UsuarioInexistente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string lb_UsuarioInexistente_ {
            get {
                return ResourceManager.GetString("lb_UsuarioInexistente ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¡Victoria!.
        /// </summary>
        public static string lb_Victoria {
            get {
                return ResourceManager.GetString("lb_Victoria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ha abandonado la sala.
        /// </summary>
        public static string msg_AbandonoSala {
            get {
                return ResourceManager.GetString("msg_AbandonoSala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código copiado.
        /// </summary>
        public static string msg_CodigoCopiado {
            get {
                return ResourceManager.GetString("msg_CodigoCopiado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debes ser anfitrión para iniciar la partida.
        /// </summary>
        public static string msg_DebesSerAnfitrion {
            get {
                return ResourceManager.GetString("msg_DebesSerAnfitrion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ahora eres anfitrión.
        /// </summary>
        public static string msg_EresAnfitrion {
            get {
                return ResourceManager.GetString("msg_EresAnfitrion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ha sido expulsado.
        /// </summary>
        public static string msg_ExpulsionSala {
            get {
                return ResourceManager.GetString("msg_ExpulsionSala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invitación enviada.
        /// </summary>
        public static string msg_InvitaciónEnviada {
            get {
                return ResourceManager.GetString("msg_InvitaciónEnviada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El usuario tiene una invitación pendiente.
        /// </summary>
        public static string msg_InvitaciónPendiente {
            get {
                return ResourceManager.GetString("msg_InvitaciónPendiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El jugador ya se encuentra en la sala.
        /// </summary>
        public static string msg_JugadorEnSala {
            get {
                return ResourceManager.GetString("msg_JugadorEnSala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No todos los jugadores están listos.
        /// </summary>
        public static string msg_JugadoresNoListos {
            get {
                return ResourceManager.GetString("msg_JugadoresNoListos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se necesitan al menos 2 jugadores para iniciar la partida.
        /// </summary>
        public static string msg_MinimoJugadores {
            get {
                return ResourceManager.GetString("msg_MinimoJugadores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a se ha unido a la sala.
        /// </summary>
        public static string msg_UnionSala {
            get {
                return ResourceManager.GetString("msg_UnionSala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya estás listo.
        /// </summary>
        public static string msg_YaEstasListo {
            get {
                return ResourceManager.GetString("msg_YaEstasListo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clic para chatear....
        /// </summary>
        public static string tb_ClicChat {
            get {
                return ResourceManager.GetString("tb_ClicChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código.
        /// </summary>
        public static string tb_Código {
            get {
                return ResourceManager.GetString("tb_Código", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código de sala.
        /// </summary>
        public static string tb_CódigoDeSala {
            get {
                return ResourceManager.GetString("tb_CódigoDeSala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo nombre de usuario.
        /// </summary>
        public static string tb_NuevoNombre {
            get {
                return ResourceManager.GetString("tb_NuevoNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambio de contraseña.
        /// </summary>
        public static string titulo_CambioContraseña {
            get {
                return ResourceManager.GetString("titulo_CambioContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambio de nombre.
        /// </summary>
        public static string titulo_CambioNombre {
            get {
                return ResourceManager.GetString("titulo_CambioNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        public static string titulo_EliminarAmigo {
            get {
                return ResourceManager.GetString("titulo_EliminarAmigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Envío de código.
        /// </summary>
        public static string titulo_EnvíoDeCódigo {
            get {
                return ResourceManager.GetString("titulo_EnvíoDeCódigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error conexión base de datos.
        /// </summary>
        public static string titulo_ErrorConexiónBD {
            get {
                return ResourceManager.GetString("titulo_ErrorConexiónBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error conexión servidor.
        /// </summary>
        public static string titulo_ErrorConexiónServidor {
            get {
                return ResourceManager.GetString("titulo_ErrorConexiónServidor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En espera de confirmación.
        /// </summary>
        public static string titulo_EsperaConfirmación {
            get {
                return ResourceManager.GetString("titulo_EsperaConfirmación", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menú.
        /// </summary>
        public static string titulo_Menu {
            get {
                return ResourceManager.GetString("titulo_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menú invitado.
        /// </summary>
        public static string titulo_MenúInvitado {
            get {
                return ResourceManager.GetString("titulo_MenúInvitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva contraseña.
        /// </summary>
        public static string titulo_NuevaContraseña {
            get {
                return ResourceManager.GetString("titulo_NuevaContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Perfil.
        /// </summary>
        public static string titulo_Perfil {
            get {
                return ResourceManager.GetString("titulo_Perfil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro.
        /// </summary>
        public static string titulo_Registro {
            get {
                return ResourceManager.GetString("titulo_Registro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sala.
        /// </summary>
        public static string titulo_Sala {
            get {
                return ResourceManager.GetString("titulo_Sala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sala invitado.
        /// </summary>
        public static string titulo_SalaInvitado {
            get {
                return ResourceManager.GetString("titulo_SalaInvitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solicitudes de amistad.
        /// </summary>
        public static string titulo_SolicitudesAmistad {
            get {
                return ResourceManager.GetString("titulo_SolicitudesAmistad", resourceCulture);
            }
        }
    }
}
