//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DobbleGame.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DobbleGame.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar foto.
        /// </summary>
        public static string btn_ActualizarFoto {
            get {
                return ResourceManager.GetString("btn_ActualizarFoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CrearSala.
        /// </summary>
        public static string btn_CrearSala {
            get {
                return ResourceManager.GetString("btn_CrearSala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entrar.
        /// </summary>
        public static string btn_Entrar {
            get {
                return ResourceManager.GetString("btn_Entrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Entrar como invitado.
        /// </summary>
        public static string btn_EntrarComoInvitado {
            get {
                return ResourceManager.GetString("btn_EntrarComoInvitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enviar código.
        /// </summary>
        public static string btn_EnviarCódigo {
            get {
                return ResourceManager.GetString("btn_EnviarCódigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar Sesión.
        /// </summary>
        public static string btn_IniciarSesión {
            get {
                return ResourceManager.GetString("btn_IniciarSesión", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registrar.
        /// </summary>
        public static string btn_Registrar {
            get {
                return ResourceManager.GetString("btn_Registrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reintentar.
        /// </summary>
        public static string btn_Reintentar {
            get {
                return ResourceManager.GetString("btn_Reintentar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unirse a sala.
        /// </summary>
        public static string btn_UnirseASala {
            get {
                return ResourceManager.GetString("btn_UnirseASala", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aceptar.
        /// </summary>
        public static string global_Aceptar {
            get {
                return ResourceManager.GetString("global_Aceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualizar.
        /// </summary>
        public static string global_Actualizar {
            get {
                return ResourceManager.GetString("global_Actualizar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string global_Cancelar {
            get {
                return ResourceManager.GetString("global_Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar contraseña.
        /// </summary>
        public static string global_ConfirmarContraseña {
            get {
                return ResourceManager.GetString("global_ConfirmarContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico.
        /// </summary>
        public static string global_CorreoElectrónico {
            get {
                return ResourceManager.GetString("global_CorreoElectrónico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva contraseña.
        /// </summary>
        public static string global_NuevaContraseña {
            get {
                return ResourceManager.GetString("global_NuevaContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ok.
        /// </summary>
        public static string global_Ok {
            get {
                return ResourceManager.GetString("global_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        public static string global_Usuario {
            get {
                return ResourceManager.GetString("global_Usuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ausente.
        /// </summary>
        public static string lb_Ausente {
            get {
                return ResourceManager.GetString("lb_Ausente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        public static string lb_Buscar {
            get {
                return ResourceManager.GetString("lb_Buscar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambio de contraseña.
        /// </summary>
        public static string lb_CambioDeContraseña {
            get {
                return ResourceManager.GetString("lb_CambioDeContraseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambio de nombre.
        /// </summary>
        public static string lb_CambioNombre {
            get {
                return ResourceManager.GetString("lb_CambioNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El formulario contiene campos vacíos.
        /// </summary>
        public static string lb_CamposVacíos {
            get {
                return ResourceManager.GetString("lb_CamposVacíos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hemos enviado un código a la dirección de correo electrónico.
        /// </summary>
        public static string lb_CódigoEnviado {
            get {
                return ResourceManager.GetString("lb_CódigoEnviado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Olvidaste tu contraseña?.
        /// </summary>
        public static string lb_ContraseñaOlvidada {
            get {
                return ResourceManager.GetString("lb_ContraseñaOlvidada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Aún no has creado una cuenta? Registrate.
        /// </summary>
        public static string lb_CrearCuenta {
            get {
                return ResourceManager.GetString("lb_CrearCuenta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El formulario contiene datos inválidos.
        /// </summary>
        public static string lb_DatosInválidos {
            get {
                return ResourceManager.GetString("lb_DatosInválidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En línea.
        /// </summary>
        public static string lb_EnLínea {
            get {
                return ResourceManager.GetString("lb_EnLínea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Envío de código.
        /// </summary>
        public static string lb_EnvíoDeCódigo {
            get {
                return ResourceManager.GetString("lb_EnvíoDeCódigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de conexión con la base de datos.
        /// </summary>
        public static string lb_ErrorConexiónBD {
            get {
                return ResourceManager.GetString("lb_ErrorConexiónBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de conexión con el servidor.
        /// </summary>
        public static string lb_ErrorConexiónServidor {
            get {
                return ResourceManager.GetString("lb_ErrorConexiónServidor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El formato seleccionado no es válido para la foto de perfil.
        /// </summary>
        public static string lb_FormatoInválido {
            get {
                return ResourceManager.GetString("lb_FormatoInválido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingresar código.
        /// </summary>
        public static string lb_IngresarCódigo {
            get {
                return ResourceManager.GetString("lb_IngresarCódigo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ingrese su nuevo nombre de usuario.
        /// </summary>
        public static string lb_IngresarNombreUsuario {
            get {
                return ResourceManager.GetString("lb_IngresarNombreUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lo sentimos, parace que hemos perdido la conexión con la base de datos, favor de intentarlo más tarde.
        /// </summary>
        public static string lb_MensajeErrorConexiónBD {
            get {
                return ResourceManager.GetString("lb_MensajeErrorConexiónBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lo sentimos, parece que hemos perdido la conexión al servidor, favor de intentarlo más tarde.
        /// </summary>
        public static string lb_MensajeErrorConexiónServidor {
            get {
                return ResourceManager.GetString("lb_MensajeErrorConexiónServidor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciaste como invitado, para comprobar todas las funciones de DOBBLE.NET inicia sesión.
        /// </summary>
        public static string lb_MensajeMenúInvitado {
            get {
                return ResourceManager.GetString("lb_MensajeMenúInvitado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro.
        /// </summary>
        public static string lb_Registro {
            get {
                return ResourceManager.GetString("lb_Registro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro realizado con éxito.
        /// </summary>
        public static string lb_RegistroExitoso {
            get {
                return ResourceManager.GetString("lb_RegistroExitoso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Código.
        /// </summary>
        public static string tb_Código {
            get {
                return ResourceManager.GetString("tb_Código", resourceCulture);
            }
        }
    }
}
